{% set name = "contes" %}
{% set version = "1.0.0" %}

about:  
    home: https://github.com/ArnaudFerre/CONTES
    license: Apache Licence 2.0
    summary: method to normalize multi-word terms with concepts from a domain-specific ontology

package:
    name: {{ name }}
    version: {{ version }}

build:
  number: 0

source:
  git_rev: 0.5	
  git_url: https://github.com/ArnaudFerre/CONTES.git
  md5: dd34a1b560832b1edea40789b720dca0

requirements:
  build:
    - python

test:
  commands:
       - ls
